[project]
name = "langchain-multi-agent-writer"
version = "0.1.0"
description = "Streamlit application for multi agents supporter on Technical document writer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain==1.0.5",
    "langchain-anthropic>=1.0.2",
    "langchain-openai>=1.0.2",
    "langchain-tavily>=0.2.13",
    "langgraph>=1.0.2",
    "matplotlib>=3.10.7",
    "networkx>=3.5",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.1",
    "streamlit>=1.40.0",
]

[tool.black]
line-length = 150

[tool.ruff]
line-length = 150

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = []

[tool.flake8]
max-line-length = 150
extend-ignore = "E203"

[tool.mypy]
python_version = "3.13"
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
